version: '3.8'
services:
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d  # run init scripts on first start

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      # Connect using the new app user instead of root
      SPRING_DATA_MONGODB_URI: mongodb://appuser:apppassword@mongo:27017/mydb

volumes:
  mongo-data:
