springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo_db
    username: demo
    password: demo

  sql:
    init:
      mode: never
